// @flow
export const LIKE_COLOR = 'LIKE_COLOR';
export const CHANGE_COLOR = 'CHANGE_COLOR';
export const REMOVE_COLOR = 'REMOVE_COLOR';
export const ADD_LIKED_COLOR = 'ADD_LIKED_COLOR';
export const ADD_LIKED_COLORS = 'ADD_LIKED_COLORS';
export const REMOVE_LIKED_COLOR = 'REMOVE_LIKED_COLOR';
export const CHANGE_LIKED_COLOR = 'CHANGE_LIKED_COLOR';

export const DISLIKE_COLOR = 'DISLIKE_COLOR';
export const ADD_DISLIKED_COLOR = 'ADD_DISLIKED_COLOR';

export const SET_IS_FETCHING = 'SET_IS_FETCHING';
export const SET_IS_STALE = 'SET_IS_STALE';
export const SET_HAS_FETCH_FAILED = 'SET_HAS_FETCH_FAILED';

export const SET_ACTIVE_COLOR_PICKER_ID = 'SET_ACTIVE_COLOR_PICKER_ID';

export const RECEIVE_PALETTE = 'RECEIVE_PALETTE';
export const REQUEST_PALETTE = 'REQUEST_PALETTE';
