// @flow
export const ADD_LIKED_COLOR = 'ADD_LIKED_COLOR';
export const ADD_LIKED_COLORS  = 'ADD_LIKED_COLORS';
export const REMOVE_LIKED_COLOR = 'REMOVE_LIKED_COLOR';
export const CHANGE_LIKED_COLOR = 'CHANGE_LIKED_COLOR';

export const DISLIKE_COLOR = 'DISLIKE_COLOR';
export const ADD_DISLIKED_COLOR = 'ADD_DISLIKED_COLOR'
