// flow-typed signature: dac2df5c0186aed8fe9cd5587231df6e
// flow-typed version: <<STUB>>/color-namer_v^1.3.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'color-namer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'color-namer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'color-namer/dist/color-namer' {
  declare module.exports: any;
}

declare module 'color-namer/dist/index' {
  declare module.exports: any;
}

declare module 'color-namer/dist/picker/jquery.mousewheel.min' {
  declare module.exports: any;
}

declare module 'color-namer/dist/picker/picker' {
  declare module.exports: any;
}

declare module 'color-namer/dist/picker/ZeroClipboard' {
  declare module.exports: any;
}

declare module 'color-namer/lib/colors/basic' {
  declare module.exports: any;
}

declare module 'color-namer/lib/colors/html' {
  declare module.exports: any;
}

declare module 'color-namer/lib/colors/ntc' {
  declare module.exports: any;
}

declare module 'color-namer/lib/colors/pantone' {
  declare module.exports: any;
}

declare module 'color-namer/lib/colors/roygbiv' {
  declare module.exports: any;
}

declare module 'color-namer/lib/colors/x11' {
  declare module.exports: any;
}

declare module 'color-namer/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'color-namer/dist/color-namer.js' {
  declare module.exports: $Exports<'color-namer/dist/color-namer'>;
}
declare module 'color-namer/dist/index.js' {
  declare module.exports: $Exports<'color-namer/dist/index'>;
}
declare module 'color-namer/dist/picker/jquery.mousewheel.min.js' {
  declare module.exports: $Exports<'color-namer/dist/picker/jquery.mousewheel.min'>;
}
declare module 'color-namer/dist/picker/picker.js' {
  declare module.exports: $Exports<'color-namer/dist/picker/picker'>;
}
declare module 'color-namer/dist/picker/ZeroClipboard.js' {
  declare module.exports: $Exports<'color-namer/dist/picker/ZeroClipboard'>;
}
declare module 'color-namer/index' {
  declare module.exports: $Exports<'color-namer'>;
}
declare module 'color-namer/index.js' {
  declare module.exports: $Exports<'color-namer'>;
}
declare module 'color-namer/lib/colors/basic.js' {
  declare module.exports: $Exports<'color-namer/lib/colors/basic'>;
}
declare module 'color-namer/lib/colors/html.js' {
  declare module.exports: $Exports<'color-namer/lib/colors/html'>;
}
declare module 'color-namer/lib/colors/ntc.js' {
  declare module.exports: $Exports<'color-namer/lib/colors/ntc'>;
}
declare module 'color-namer/lib/colors/pantone.js' {
  declare module.exports: $Exports<'color-namer/lib/colors/pantone'>;
}
declare module 'color-namer/lib/colors/roygbiv.js' {
  declare module.exports: $Exports<'color-namer/lib/colors/roygbiv'>;
}
declare module 'color-namer/lib/colors/x11.js' {
  declare module.exports: $Exports<'color-namer/lib/colors/x11'>;
}
declare module 'color-namer/test/index.js' {
  declare module.exports: $Exports<'color-namer/test/index'>;
}
